config/routes.rb
ForumApp::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "stats" => "users#rank", :as => "stats"
  get "admin" => "users#index", :as => "admin"
  get "admin/followers" => "followers#index", :as => "admin/followers"
  get "terms" => "terms#show", :as => "terms"
  root :to => "posts#index"

  post "comments/:id" => "comments#update"

  resources :users do 
    member do
      get 'make_admin'
      get 'make_not_admin'
      get 'make_mod'
      get 'make_not_mod'
      get 'dismiss_all_notifications'
      get 'refresh'
    end
  end
  
  resources :sessions
  resources :posts do 
    member do
      get 'lock'
      get 'unlock'
    end
  end
  resources :comments
  resources :ncomments
  resources :notifications
  resources :plusones
  resources :forums
  resources :followers
  resources :password_resets
  resources :requests
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id, :comment_updated_at, :comment_updated_by
  belongs_to :user
  belongs_to :post
  has_many :ncomments
  has_many :plusones
  validates_presence_of :content
  validates_length_of :content, :minimum => 1
  before_save :test_whitespace

  private
  def test_whitespace
    if self.content.strip.length == 0
      self.content.length = 0
    end
  end
end

app/models/error.rb
class Error < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :post_id, :user_id
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :user_id, :scope => [:post_id]
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :title
  has_many :posts
end

app/models/ncomment.rb
class Ncomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
  attr_accessible :comment_id, :content, :user_id
  validates_presence_of :content
  validates_length_of :content, :minimum => 1
  before_save :test_whitespace

  private

  def test_whitespace
  	if self.content.strip.length == 0
  		self.content.length = 0
  	end
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
end

app/models/plusone.rb
class Plusone < ActiveRecord::Base
  attr_accessible :comment_id, :user_id
  belongs_to :user
  belongs_to :comment
  validates_uniqueness_of :user_id, :scope => [:comment_id]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :followers
  belongs_to :forum
  attr_accessible :content, :title, :user_id, :forum_id, :post_updated_at, :post_updated_by, :locked
  validates_length_of :title, :minimum => 2
  validates_length_of :content, :minimum => 5
  before_save :test_whitespace

  def self.search(search)
    if search
      where('title Like ?', '%#{search}%')
    else
      scoped
    end
  end

  private
  def test_whitespace
    if self.content.strip.length == 0
      self.content.length = 0
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :header
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :password, :password_confirmation, :aboutme, :sociallink, :linkedin, :twitter, :github, :gplus, :admin, :moderator, :terms

  has_many :posts
  has_many :comments
  has_many :ncomments
  has_many :plusones
  has_many :notifications
  
  before_create { generate_token(:auth_token) }

  validates_acceptance_of :terms
  validates_presence_of :name
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_uniqueness_of :name
  validates :email, :presence => true, :email => true
  validates_length_of :password, :minimum => 6

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.authenticate(email,password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  		user
  	else
  		nil
  	end
  end

  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end

  def dismiss_notifications
    if self.notifications.length > 0
      self.notifications.each do |n|
        n.destroy
      end
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/plusones_helper.rb
module PlusonesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum | JoahG.com</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :rails %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    // to set WMD's options programatically, define a "wmd_options" object with whatever settings
    // you want to override.  Here are the defaults:
    wmd_options = {
      // format sent to the server.  Use "Markdown" to return the markdown source.
      output: "Markdown"
    };
  </script>
</head>
<body>
  <div class="navbar navbar-inverse navbar-top navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
          <div class="nav-collapse collapse">
            <nav class="left">
              <ul class="nav">
                <% if !current_page?(posts_path) && !current_page?(root_path) %>
                  <li class="">
                    <%= link_to "Home", root_url %>
                  </li>
                <% else %>
                  <li class="">
                    <a href="#">Home</a>
                  </li>
                <%end%>
                <li class="">
                  <a href="/stats">Stats</a>
                </li>
                <% if current_user %>
                  <% if current_user.admin? %>
                    <li class="">
                      <%= link_to "Admin Page", "/admin" %>
                    </li>
                  <% end %>
                  <li class="">
                    <%= link_to 'New Post', new_post_path %>
                  </li>
                <%else%>
                  <li class="">
                    <%= link_to "Sign Up", sign_up_path %>
                  </li>
                <% end %>
              </ul>
            </nav>
            <nav class="right">
              <%if current_user%>
                <ul class="nav">
                  <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="arrow"></span>
                     <%= image_tag avatar_url(current_user, 16), :class => 'current_user_pic' %> &nbsp; <%= current_user.name %>
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to 'View my profile', current_user %>
                      </li>
                      <li>
                        <%= link_to 'Edit my account', edit_user_path(current_user) %>
                      </li>
                      <li class="">
                        <%= link_to "Log Out", log_out_path %>
                      </li>
                    </ul>
                  </li>
                  <li class="notifications_update">
                    <%=link_to pluralize(current_user.notifications.length, 'notification'), "/users/#{current_user.id.to_s}#n", :class => "notifications_button" %>
                  </li>
                </ul>
              <%else%>
                <%= form_tag sessions_path, :class => 'navbar-form pull-left' do %>
                  <%= email_field_tag :email, params[:email], :placeholder =>'Email Address' %>
                  <%= password_field_tag :password,nil, :placeholder => 'Password' %>
                  <%= submit_tag "Log in", :class => 'btn' %>
                  <%= check_box_tag :remember_me, 1, params[:remember_me] %>
                <% end %>
              <%end%>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="page_loading">
    <div class="container center">
      <img src="/assets/loading.gif">
    </div>
  </div>
  <div class="container" id="content-container">
<%= yield %>
  </div>
  <% if !@user %>
    <footer class="navbar container">
      <div>
        <div class="container">
          <nav class="left">
            <ul class="nav">
              <li><a class="notalink">All Content &copy; Popcorn Web Development 2013</a></li>
            </ul>
          </nav>
          <nav class="right">
            <ul class="nav">
              <li><a href="http://popcorn-web-development.github.com">About Us</a></li>
              <li><a href="/terms">Terms Of Service</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </footer>
  <%end%>
</body>
</html>